name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install
          npm install electron-builder --save-dev

      - name: Build and publish for Mac
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          npm run build
          npx electron-builder build --mac --publish always

      - name: Build and publish for Windows
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          npm run build
          npx electron-builder build --windows --publish always

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: 'Automatic release from CI'
          draft: true
          prerelease: false