name: macOS

on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install
          npm install electron-builder --save-dev

      - name: Build and publish for Mac
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          npm run build
          npx electron-builder build --mac --publish always