name: Windows

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build and publish for Windows
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          npm run build
          npx electron-builder build --windows --publish always
